### ISSUE TITLE
I2C Status Register Values

### ISSUE THREAD

**Issue by kowalski100** [polarfire-soc/polarfire-soc-bare-metal-library#16]
I did a quick match of I2C_STATUS register (attached) with values given in driver [here](https://github.com/polarfire-soc/polarfire-soc-bare-metal-library/blob/6a093aa9570180170a3874ecbed78a658666cf7d/src/platform/drivers/mss/mss_i2c/mss_i2c.c#L38). The register doesn't mention all the values mentioned in the driver. Where are other values like **ST_SLAR_ACK** taken from?

Also is there any way to disable I2C interrupt locally - I mean not from interrupt controller but from I2C registers?

![status-reg](https://user-images.githubusercontent.com/7781522/129151834-51f2b371-c0fd-4ea1-8774-16aa5850039d.PNG)

**Comment by kowalski100** [comment]
Any updates on this?

**Comment by nitindeshpande** [comment]
Hello,
 Looks like some values are missing from the description. We are looking into it. Will get back soon,

**Comment by nitindeshpande** [comment]
@kowalski100 
Confirming the issue. The status register has different values based on the current mode of operation. The register description only describes the values in Master Transmit mode. Values when the core is in other modes are not documented.
Will get this corrected. Thanks for pointing out.

**Comment by kowalski100** [comment]
Hi @nitindeshpande Thanks for your reply.

Closing this issue and waiting for your reply confirming documentation update.

**Comment by kowalski100** [comment]
Hi @nitindeshpande Thanks for your reply.

Closing this issue and waiting for your reply confirming documentation update.
