### ISSUE TITLE
Periodic IRQ Example with Icicle Kit (Rev 1.0)

### ISSUE THREAD

**Issue by Jesse-Millwood** [polarfire-soc/polarfire-soc-bare-metal-library#2]
### Background
I am trying to get the mpfs periodic irq example to run on my Icicle Kit over JTAG. 
My kit came with a Flash Pro 5 so I have J9 open and have the Flash Pro 5 connected to the JTAG connector. 

### Issue
I was able to build the example in SoftConsole v6.5 and run it in the Renode emulator. However, I cannot get the "Run As" or "Debug As" choices to work. I don't see output on the serial terminals when I choose the "Run As" choice. When I try the "Debug As" choice I get an error which looks like it is related to a gdb command. 

### Running over JTAG
When I go to run the `mpfs-periodic-irq hw all-harts debug.launch` by right clicking on the file in the Project Explorer and choosing "Run As" and choosing the `mpfs-periodic-irq hw all-harts debug.launch` option I don't see any output on any of the terminals. 

The Eclicpse Console Output displays the following output: 
```
fpServer v17 waiting for incoming connections on the port 3334 with API v5
Device not found
Info : 1 1607540776825 microsemi_flashpro_server.c:1751 microsemi_flashpro_initialize() FlashPro ports available: S20153T6AV
Info : 2 1607540776825 microsemi_flashpro_server.c:1752 microsemi_flashpro_initialize() FlashPro port selected:   S20153T6AV
xPack OpenOCD (Microchip SoftConsole build), x86_64 Open On-Chip Debugger 0.10.0+dev-00859-g95a8cd9b5-dirty (2020-10-19-17:28)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
MPFS
Info : only one transport option; autoselect 'jtag'
Info : Hardware thread awareness created
do_board_reset_init
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : No Embedded FlashPro6 (revision B) devices found
Info : clock speed 6000 kHz
Info : JTAG tap: mpfs.cpu tap/device found: 0x0f81a1cf (mfg: 0x0e7 (GateField), part: 0xf81a, ver: 0x0)
Info : datacount=2 progbufsize=16
Info : Disabling abstract command reads from CSRs.
Info : Core 0 could not be made part of halt group 1.
Info : Examined RISC-V core; found 5 harts
Info :  hart 0: XLEN=64, misa=0x8000000000101105
Info :  hart 1: currently disabled
Info :  hart 2: currently disabled
Info :  hart 3: currently disabled
Info :  hart 4: currently disabled
Info : datacount=2 progbufsize=16
Info : Disabling abstract command reads from CSRs.
Info : Core 1 could not be made part of halt group 1.
Info : Examined RISC-V core; found 5 harts
Info :  hart 0: currently disabled
Info :  hart 1: XLEN=64, misa=0x800000000014112d
Info :  hart 2: currently disabled
Info :  hart 3: currently disabled
Info :  hart 4: currently disabled
Info : datacount=2 progbufsize=16
Info : Disabling abstract command reads from CSRs.
Info : Core 2 could not be made part of halt group 1.
Info : Examined RISC-V core; found 5 harts
Info :  hart 0: currently disabled
Info :  hart 1: currently disabled
Info :  hart 2: XLEN=64, misa=0x800000000014112d
Info :  hart 3: currently disabled
Info :  hart 4: currently disabled
Info : datacount=2 progbufsize=16
Info : Disabling abstract command reads from CSRs.
Info : Core 3 could not be made part of halt group 1.
Info : Examined RISC-V core; found 5 harts
Info :  hart 0: currently disabled
Info :  hart 1: currently disabled
Info :  hart 2: currently disabled
Info :  hart 3: XLEN=64, misa=0x800000000014112d
Info :  hart 4: currently disabled
Info : datacount=2 progbufsize=16
Info : Disabling abstract command reads from CSRs.
Info : Core 4 could not be made part of halt group 1.
Info : Examined RISC-V core; found 5 harts
Info :  hart 0: currently disabled
Info :  hart 1: currently disabled
Info :  hart 2: currently disabled
Info :  hart 3: currently disabled
Info :  hart 4: XLEN=64, misa=0x800000000014112d
Info : Listening on port 3333 for gdb connections
Started by GNU MCU Eclipse
Info : accepting 'gdb' connection on tcp/3333
Info : New GDB Connection: 1, Target mpfs.hart0_e51, state: halted
Info : Disabling abstract command writes to CSRs.
Info : Disabling abstract command writes to CSRs.
Info : Disabling abstract command writes to CSRs.
Info : Disabling abstract command writes to CSRs.
Info : Disabling abstract command writes to CSRs.
Warn : negative acknowledgment, but no packet pending
Warn : negative acknowledgment, but no packet pending
Warn : negative acknowledgment, but no packet pending
Warn : negative acknowledgment, but no packet pending
Warn : negative acknowledgment, but no packet pending
Warn : negative acknowledgment, but no packet pending
Warn : negative acknowledgment, but no packet pending
===== RISC-V Registers
(0) zero (/64): 0x0000000000000000
(1) ra (/64): 0x0000000008002D10
(2) sp (/64): 0x000000000800A380
(3) gp (/64): 0x0000000008006AA0
(4) tp (/64): 0x000000000800A3C0
(5) t0 (/64): 0x8000000000101105
(6) t1 (/64): 0x0000000000000000
(7) t2 (/64): 0x0000000000000000
(8) fp (/64): 0x0000000000000000
(9) s1 (/64): 0x0000000000000000
(10) a0 (/64): 0x0000000000000003
(11) a1 (/64): 0x0000000008000000
(12) a2 (/64): 0x0000000008006220
(13) a3 (/64): 0x000000000800A800
(14) a4 (/64): 0x0000000000000001
(15) a5 (/64): 0x000000000800B3C0
(16) a6 (/64): 0x0000000000000000
(17) a7 (/64): 0x0000000000000000
(18) s2 (/64): 0x0000000000000000
(19) s3 (/64): 0x0000000000000000
(20) s4 (/64): 0x0000000000000000
(21) s5 (/64): 0x0000000000000000
(22) s6 (/64): 0x0000000000000000
(23) s7 (/64): 0x0000000000000000
(24) s8 (/64): 0x0000000000000000
(25) s9 (/64): 0x0000000000000000
(26) s10 (/64): 0x0000000000000000
(27) s11 (/64): 0x0000000000000000
(28) t3 (/64): 0x0000000000000000
(29) t4 (/64): 0x0000000000000000
(30) t5 (/64): 0x0000000000000000
(31) t6 (/64): 0x0000000000000000
(32) pc (/64)
(65) ustatus (/64)
(69) uie (/64)
(70) utvec (/64)
(72) utvt (/64)
(129) uscratch (/64)
(130) uepc (/64)
(131) ucause (/64)
(132) utval (/64)
(133) uip (/64)
(134) unxti (/64)
(135) uintstatus (/64)
(137) uscratchcsw (/64)
(138) uscratchcswl (/64)
(323) sedeleg (/64)
(324) sideleg (/64)
(328) stvt (/64)
(390) snxti (/64)
(391) sintstatus (/64)
(393) sscratchcsw (/64)
(394) sscratchcswl (/64)
(577) vsstatus (/64)
(581) vsie (/64)
(582) vstvec (/64)
(641) vsscratch (/64)
(642) vsepc (/64)
(643) vscause (/64)
(644) vstval (/64)
(645) vsip (/64)
(705) vsatp (/64)
(833) mstatus (/64): 0x0000000200001800
(834) misa (/64)
(837) mie (/64)
(838) mtvec (/64)
(839) mcounteren (/64)
(840) mtvt (/64)
(865) mcountinhibit (/64)
(868) mhpmevent3 (/64)
(869) mhpmevent4 (/64)
(870) mhpmevent5 (/64)
(871) mhpmevent6 (/64)
(872) mhpmevent7 (/64)
(873) mhpmevent8 (/64)
(874) mhpmevent9 (/64)
(875) mhpmevent10 (/64)
(876) mhpmevent11 (/64)
(877) mhpmevent12 (/64)
(878) mhpmevent13 (/64)
(879) mhpmevent14 (/64)
(880) mhpmevent15 (/64)
(881) mhpmevent16 (/64)
(882) mhpmevent17 (/64)
(883) mhpmevent18 (/64)
(884) mhpmevent19 (/64)
(885) mhpmevent20 (/64)
(886) mhpmevent21 (/64)
(887) mhpmevent22 (/64)
(888) mhpmevent23 (/64)
(889) mhpmevent24 (/64)
(890) mhpmevent25 (/64)
(891) mhpmevent26 (/64)
(892) mhpmevent27 (/64)
(893) mhpmevent28 (/64)
(894) mhpmevent29 (/64)
(895) mhpmevent30 (/64)
(896) mhpmevent31 (/64)
(897) mscratch (/64)
(898) mepc (/64)
(899) mcause (/64)
(900) mtval (/64)
(901) mip (/64)
(902) mnxti (/64)
(903) mintstatus (/64)
(905) mscratchcsw (/64)
(906) mscratchcswl (/64)
(993) pmpcfg0 (/64)
(995) pmpcfg2 (/64)
(1009) pmpaddr0 (/64)
(1010) pmpaddr1 (/64)
(1011) pmpaddr2 (/64)
(1012) pmpaddr3 (/64)
(1013) pmpaddr4 (/64)
(1014) pmpaddr5 (/64)
(1015) pmpaddr6 (/64)
(1016) pmpaddr7 (/64)
(1017) pmpaddr8 (/64)
(1018) pmpaddr9 (/64)
(1019) pmpaddr10 (/64)
(1020) pmpaddr11 (/64)
(1021) pmpaddr12 (/64)
(1022) pmpaddr13 (/64)
(1023) pmpaddr14 (/64)
(1024) pmpaddr15 (/64)
(1601) hstatus (/64)
(1603) hedeleg (/64)
(1604) hideleg (/64)
(1607) hcounteren (/64)
(1729) hgatp (/64)
(2017) tselect (/64)
(2018) tdata1 (/64)
(2019) tdata2 (/64)
(2020) tdata3 (/64)
(2033) dcsr (/64)
(2034) dpc (/64)
(2035) dscratch (/64)
(2881) mcycle (/64)
(2883) minstret (/64)
(2884) mhpmcounter3 (/64)
(2885) mhpmcounter4 (/64)
(2886) mhpmcounter5 (/64)
(2887) mhpmcounter6 (/64)
(2888) mhpmcounter7 (/64)
(2889) mhpmcounter8 (/64)
(2890) mhpmcounter9 (/64)
(2891) mhpmcounter10 (/64)
(2892) mhpmcounter11 (/64)
(2893) mhpmcounter12 (/64)
(2894) mhpmcounter13 (/64)
(2895) mhpmcounter14 (/64)
(2896) mhpmcounter15 (/64)
(2897) mhpmcounter16 (/64)
(2898) mhpmcounter17 (/64)
(2899) mhpmcounter18 (/64)
(2900) mhpmcounter19 (/64)
(2901) mhpmcounter20 (/64)
(2902) mhpmcounter21 (/64)
(2903) mhpmcounter22 (/64)
(2904) mhpmcounter23 (/64)
(2905) mhpmcounter24 (/64)
(2906) mhpmcounter25 (/64)
(2907) mhpmcounter26 (/64)
(2908) mhpmcounter27 (/64)
(2909) mhpmcounter28 (/64)
(2910) mhpmcounter29 (/64)
(2911) mhpmcounter30 (/64)
(2912) mhpmcounter31 (/64)
(3137) cycle (/64)
(3138) time (/64)
(3139) instret (/64)
(3140) hpmcounter3 (/64)
(3141) hpmcounter4 (/64)
(3142) hpmcounter5 (/64)
(3143) hpmcounter6 (/64)
(3144) hpmcounter7 (/64)
(3145) hpmcounter8 (/64)
(3146) hpmcounter9 (/64)
(3147) hpmcounter10 (/64)
(3148) hpmcounter11 (/64)
(3149) hpmcounter12 (/64)
(3150) hpmcounter13 (/64)
(3151) hpmcounter14 (/64)
(3152) hpmcounter15 (/64)
(3153) hpmcounter16 (/64)
(3154) hpmcounter17 (/64)
(3155) hpmcounter18 (/64)
(3156) hpmcounter19 (/64)
(3157) hpmcounter20 (/64)
(3158) hpmcounter21 (/64)
(3159) hpmcounter22 (/64)
(3160) hpmcounter23 (/64)
(3161) hpmcounter24 (/64)
(3162) hpmcounter25 (/64)
(3163) hpmcounter26 (/64)
(3164) hpmcounter27 (/64)
(3165) hpmcounter28 (/64)
(3166) hpmcounter29 (/64)
(3167) hpmcounter30 (/64)
(3168) hpmcounter31 (/64)
(3922) mvendorid (/64)
(3923) marchid (/64)
(3924) mimpid (/64)
(3925) mhartid (/64)
(4161) priv (/8)

```

### Debugging Over JTAG

When I go to run the `mpfs-periodic-irq hw all-harts debug.launch` by right clicking on the file in the Project Explorer and choosing "Debug As" and choosing the `mpfs-periodic-irq hw all-harts debug.launch` option I get the same output but when I set a breakpoint on something like line 46 of `e51.c` I get a "Problem Occurred" window. The contents of it say: 
```
Error in final launch sequence
Failed to execute MI command:
thread apply all set $pc=_start
Error message from debugger back end:
Unknown remote qXfer reply: 97370000 ,Failed to execute MI command:
tbreak e51
Error message from debugger back end:
Reply contains invalid hex digit 108
Failed to execute MI command:
thread apply all set $pc=_start
Error message from debugger back end:
Unknown remote qXfer reply: 97370000
Unknown remote qXfer reply: 97370000
Failed to execute MI command:
tbreak e51
Error message from debugger back end:
Reply contains invalid hex digit 108
Reply contains invalid hex digit 108
```

### Other Information

Host OS: Ubuntu 18.04

**Comment by hughbreslin** [comment]
Hey Jesse 🙂 

Hmm this is an interesting one, I tried building and debugging this project and it connected straight away and I got a UART output. Its hard to see whats going wrong from the information you've got up so far:

1. You should be seeing something similar to whats shown here: https://youtu.be/BY3306ITDhM?list=PL9B4edd-p2ahc3AQdBAmGfAyo_pcDW0Tg&t=143 - does it just never get to the breakpoint at the e51 function for you to resume it?

2. If its never reaching e51, once you get to the last stages of the debug session starting can you halt the core and see where its currently executing? In the video I sent you can see the threads listed in the bottom left at 2:50 showing the current execution address - it'd be interesting to see where its getting stuck

3. Have you tried a different bare metal example and did that run? The mmuart-interrupt example is a good one to try

**Comment by AntonKrug** [comment]
Could you try following?

- Go to Run-> Debug configurations
- Select that specific launcher and then go to the Debugger tab
- In the GDB Client Setup section where it has executable name "${cross_prefix}gdb${cross_suffix}" click on browse
- Navigate to the SC 6.5 RISCV gdb binary manually <SC_INSTALL_DIRECTORY>/riscv-unknown-elf-gcc/bin/riscv64-unknown-elf-gdb and select it instead of the macro
- Then click Debug button

**Comment by Jesse-Millwood** [comment]
> Hey Jesse slightly_smiling_face
> 
> Hmm this is an interesting one, I tried building and debugging this project and it connected straight away and I got a UART output. Its hard to see whats going wrong from the information you've got up so far:
> 
>     1. You should be seeing something similar to whats shown here: https://youtu.be/BY3306ITDhM?list=PL9B4edd-p2ahc3AQdBAmGfAyo_pcDW0Tg&t=143 - does it just never get to the breakpoint at the e51 function for you to resume it?
> 
>     2. If its never reaching e51, once you get to the last stages of the debug session starting can you halt the core and see where its currently executing? In the video I sent you can see the threads listed in the bottom left at 2:50 showing the current execution address - it'd be interesting to see where its getting stuck
> 
>     3. Have you tried a different bare metal example and did that run? The mmuart-interrupt example is a good one to try

Thanks for your reply @hughbreslin! For comparison's sake, I started the video from the beginning with the mmuart-interrupt example and followed up until the breakpoint happened on the e51. Mine does not seem to hit the breakpoint. When I click the suspend button in the top toolbar, I can see the `mpfs-mmuart-interrupt.elf [cores: 1,2,3,4,5]` line of the Debug tab in the lower left hand window has a pause icon on it. However, nothing pops up for me. I would expect a source file to pop up to show me where it is stopped the way it would if I did it with Renode. I do not seem to be able to actually halt it and see where it is and nothing prints on the my serial terminals. Do you have any other ideas? Thanks

**Comment by Jesse-Millwood** [comment]
> Could you try following?
> 
>     * Go to Run-> Debug configurations
> 
>     * Select that specific launcher and then go to the Debugger tab
> 
>     * In the GDB Client Setup section where it has executable name "${cross_prefix}gdb${cross_suffix}" click on browse
> 
>     * Navigate to the SC 6.5 RISCV gdb binary manually <SC_INSTALL_DIRECTORY>/riscv-unknown-elf-gcc/bin/riscv64-unknown-elf-gdb and select it instead of the macro
> 
>     * Then click Debug button

@AntonKrug thanks for the tip! This sadly did not lead to any new output. This is what I see after I wait a couple minutes after hitting debug: 
![image](https://user-images.githubusercontent.com/5342237/101786656-2c8b5400-3acc-11eb-8940-9f710e7e6c71.png)

**Comment by Jesse-Millwood** [comment]
@hughbreslin and @AntonKrug , 
For what it's worth, I should also say that I can get Linux to boot from the SD card after I followed the instructions at [Updating the Icicle Kit](https://github.com/polarfire-soc/polarfire-soc-documentation/blob/master/boards/mpfs-icicle-kit-es/updating-icicle-kit/updating-icicle-kit-design-and-linux.md). So I don't think that my board is defective.

My main reason for going down this rabbit hole is that I can't seem to get the mss timer interrupt to fire when booting from the SD card. I am assuming it is the bootloader in the EMMC but I want to verify everything is working on the baremetal first. My code works on Renode when booting using the BBL so there is something different, I'm just trying to figure out what.

**Comment by Jesse-Millwood** [comment]
@hughbreslin and @AntonKrug 
What is the state of your jumpers? Do they all follow the default settings in [the user guide](https://www.microsemi.com/document-portal/doc_download/1245042-ug0882-polarfire-soc-fpga-icicle-kit-user-guide)? What JTAG programmer are you using? I tried the onboard one and closing Jumper J9 but console reported an early failure that looked like it couldn't find it. Have you tried a FlashPro5 or FlashPro6?

**Comment by Jesse-Millwood** [comment]
I actually just got it working! 
I had to run into the office to grab a FlashPro6 and that worked! 

It's odd that the Icicle Kit came with a FlashPro5. Using it as a JTAG debugger did not seem to work and neither did the onboard one.

**Comment by hughbreslin** [comment]
@Jesse-Millwood great glad its working🙂 

I haven't had any issues using a FlashPro5 but I'm on a Windows host so theres a difference there... You can get the onboard FlashPro6 working by following the steps in section 1.2 of the [Libero 12.5 SP1 RN](https://coredocs.s3.amazonaws.com/Libero/12_5_1/libero_soc_v12_5_1_release_notes.pdf)

**Comment by Jesse-Millwood** [comment]
@hughbreslin Thanks for the pointer there. I'll have to see if I can get Libero working. My IT was having trouble with the FlexLM license working on our server before. I'll have to check and see we are still having those issues.

**Comment by hughbreslin** [comment]
You actually only need flashpro express which doesn't need a license :) so you can avoid flexlm issues

**Comment by Jesse-Millwood** [comment]
@hughbreslin thanks for your help! I just saw the Libero part and didn't read the rest. There seems to be an issue with using FPExpress and the job file but I have the external debugger working now so I'll just stick with that. I appreciate your help!

**Comment by AntonKrug** [comment]
@Jesse-Millwood Depending on the eFP6 firmware on your board you might not even need flashpro express, just make sure J9 and J24 are properly set and it should work straight away (if you have a board with the newer eFP6 firmware)
