### ISSUE TITLE
An isssue with mpfs-uart-mac-freertos_lwip application

### ISSUE THREAD

**Issue by OrlyShdema** [polarfire-soc/polarfire-soc-bare-metal-library#4]
Hello,

I am unable to run the mpfs-uart-mac-freertos_lwip application  on the Icicile kit.

are there any known issues with this application code?
is it suppose to work on the factory settings and programming file  of  PF-SOC?

Pls. advise.
Thanks,
Orly

**Comment by petermcs-01** [comment]
Hi Orly,

What behavior are you seeing? The example should work ok but you will need to check the readme for details of the IP address setup to use etc.

Regards,
Peter

**Comment by nitindeshpande** [comment]
@OrlyShdema, were you able to test the project further? Are we good to close this issue?

**Comment by nitindeshpande** [comment]
Assuming that this is no more an issue.
